# Generated by Django 4.2.4 on 2023-09-05 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="message",
            new_name="question",
        ),
    ]
