# Generated by Django 4.2.4 on 2023-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_rename_message_chathistory_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
